name: Pylint

on: [push]

jobs:
  runs-on: ubuntu-latest
  job_id:
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: actions/checkout@v3

    - id: auth
      uses: google-github-actions/auth@v0
      with:
        service_account: 'deployer@image-bot-346319.iam.gserviceaccount.com'
        credentials_json: '${{ secrets.GC_TOKEN }}'

    - id: 'deploy'
      uses: 'google-github-actions/deploy-cloud-functions@v0'
      with:
        name: 'my-function'
        runtime: 'python3'

    # Example of using the output
    - id: 'test'
      run: 'curl "${{ steps.deploy.outputs.url }}"'
